'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddProperty
    
    '''<summary>
    '''scriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''hidCustomerId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCustomerId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPropertyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPropertyId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidSelectedPropertyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSelectedPropertyId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPropertyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPropertyImage As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapProperty As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentImpacts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentImpacts1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentImpacts2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentImpacts2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentImpacts3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentImpacts3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentBenefits1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentBenefits1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentBenefits2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentBenefits2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentBenefits3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentBenefits3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidAssignProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAssignProperty As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidCropFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCropFile As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidDisplayMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDisplayMode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''aOverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aOverView As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateValueMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateValueMap As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateProperty As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCompareDecide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCompareDecide As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAddProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkIncludeArchieve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeArchieve As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divViewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divViewProperty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAddProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddProperty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPropertyStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropertyStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPropertyError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPropertyError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProperties As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtPropertyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPropertyName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtSquareFeet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSquareFeet As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBedRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBedRooms As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBaths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBaths As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPrimaryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimaryAddress As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPrimaryCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimaryCity As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPrimaryState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimaryState As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPrimaryZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimaryZip As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPrimaryCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimaryCountry As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chkArchieve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkArchieve As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''fupPhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fupPhoto1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''fupPhoto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fupPhoto2 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''rfvPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPrice As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rfvPropertyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPropertyName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rfvddlProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvddlProperties As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rfvStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvStreet As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rfvCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCity As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rfvState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvState As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rfvZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvZip As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ValidatorCalloutExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender2 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''ValidatorCalloutExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender1 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''ValidatorCalloutExtender6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender6 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''ValidatorCalloutExtender7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender7 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''ValidatorCalloutExtender8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender8 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''ValidatorCalloutExtender9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender9 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''regexPrimaryZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexPrimaryZip As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''ValidatorCalloutExtender10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender10 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''ValidatorCalloutExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorCalloutExtender3 As Global.AjaxControlToolkit.ValidatorCalloutExtender
    
    '''<summary>
    '''divPropertyActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPropertyActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSaveProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblUSPSMessageError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUSPSMessageError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblHomeAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHomeAddress As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblUSPSCurrentAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUSPSCurrentAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUSPSStreetAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUSPSStreetAddr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblSuggest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSuggest As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''btnUSPSUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUSPSUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUSPSCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUSPSCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrevious As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCropImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCropImage As Global.System.Web.UI.WebControls.Button
End Class
