'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompareDecide
    
    '''<summary>
    '''hidCustomerId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCustomerId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPropertyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPropertyId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidSelectedPropertyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSelectedPropertyId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPropertyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPropertyImage As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapProperty As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentImpacts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentImpacts1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentImpacts2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentImpacts2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentImpacts3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentImpacts3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentBenefits1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentBenefits1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentBenefits2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentBenefits2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapPropertyContentBenefits3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapPropertyContentBenefits3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''aOverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aOverView As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateValueMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateValueMap As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateProperty As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCompareDecide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCompareDecide As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divViewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divViewProperty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
