'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Overview
    
    '''<summary>
    '''hidPropertyContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPropertyContent As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCustomerID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''aOverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aOverView As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateValueMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateValueMap As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateProperty As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCompareDecide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCompareDecide As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lnkCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCustomerName As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCustomerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkEditContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEditContact As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnSendVMLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendVMLink As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRedirectVMOLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirectVMOLink As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRedirectVMLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirectVMLink As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddToDo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddToDo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pVMLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pVMLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriority1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriority1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblImpact1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpact1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrent1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFuture1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuture1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBenefits1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBenefits1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriority2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriority2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblImpact2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpact2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrent2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFuture2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuture2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBenefits2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBenefits2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriority3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriority3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblImpact3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpact3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrent3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrent3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFuture3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuture3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBenefits3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBenefits3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblPropertyOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPropertyOverview As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblViewContactSecondaryFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactSecondaryFirstName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactSecondaryLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactSecondaryLastName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactFirstName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactLastName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactCommunity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactVMCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactVMCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactWorkPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactWorkPhone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactMobilePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactMobilePhone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactStreetAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactCity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactState As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactZip As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblViewContactNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewContactNotes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divHtmlContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHtmlContent As Global.System.Web.UI.WebControls.HiddenField
End Class
