'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ValueMapdupe
    
    '''<summary>
    '''hidPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPriority As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidCustId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCustId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPriorityId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPriorityId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPriorityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPriorityName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidCustomerPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCustomerPriority As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidQuestionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidQuestionType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidSelectedPriorities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSelectedPriorities As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidImpactAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidImpactAnswer As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidValueMapQuestionDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidValueMapQuestionDisplay As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''aOverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aOverView As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateValueMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateValueMap As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCreateProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCreateProperty As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aCompareDecide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCompareDecide As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnVmReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVmReview As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''divValueGapTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divValueGapTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''create_pdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents create_pdf As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''divValueGapContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divValueGapContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divValueGap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divValueGap As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScore As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblValueGap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueGap As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblValueGapProbability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueGapProbability As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblValueMapTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueMapTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriorityOverView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriorityOverView As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPrintCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintCustomerName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrintUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrintUserPhoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintUserPhoneNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divPriority1Impacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority1Impacts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblImpactsScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpactsScore1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority1CSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority1CSDesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriority1Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriority1Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority1FSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority1FSDesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority1FSBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority1FSBenefits As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBenefitScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBenefitScore1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority2Impacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority2Impacts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblImpactsScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpactsScore2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority2CSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority2CSDesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriority2Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriority2Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority2FSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority2FSDesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority2FSBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority2FSBenefits As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBenefitScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBenefitScore2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority3Impacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority3Impacts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblImpactsScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpactsScore3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority3CSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority3CSDesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriority3Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriority3Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority3FSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority3FSDesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority3FSBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority3FSBenefits As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBenefitScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBenefitScore3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEditPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEditPriority As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriority As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriorities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriorities As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPreviousPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousPriority As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextPriority As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRank As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPriorityRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPriorityRank As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblItem1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItem1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblItem2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItem2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblItem3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItem3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPreviousRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousRank As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextRank As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divCSFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSFuture As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriorityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriorityName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFuture As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPreviousFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousFuture As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextFuture As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divCSCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSCurrent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriorityCurrentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriorityCurrentTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCSFutureContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSFutureContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCSFutureChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSFutureChoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCSCurrentContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSCurrentContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCSCurrentChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSCurrentChoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPreviousCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousCurrent As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextCurrent As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divCSImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSImpact As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divImpact As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPreviousImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousImpact As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextImpact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextImpact As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divCSBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSBenefit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBenefit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPreviousBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousBenefit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextBenefit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divEditModalContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEditModalContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCSCurrentContentEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSCurrentContentEdit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCSCurrentChoiceEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSCurrentChoiceEdit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPreviousScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousScore As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextScore As Global.System.Web.UI.WebControls.Button
End Class
