'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VMCategoryMaint
    
    '''<summary>
    '''scriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''upGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upGroup As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divGroupError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGroupError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblGroupError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvGroups As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCategory As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCategoryError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divGroupCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGroupCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dropDialogGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogGroups As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnCopyCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divCopyGroupCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCopyGroupCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dropDialogCurrentGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogCurrentGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dropDialogCopyGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogCopyGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dropDialogCopyGroupCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogCopyGroupCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSubmitCopyCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitCopyCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelCopyCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelCopyCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCategories As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCommunity As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divCommunityError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommunityError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCommunityError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommunityError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dropDialogCommunityGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogCommunityGroups As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvCommunities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCommunities As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upCommunityCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCommunityCategory As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divCommunityCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommunityCategoryError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCommunityCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommunityCategoryError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dropDialogCommunityCategoryGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogCommunityCategoryGroups As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dropDialogCommunityCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogCommunityCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvCommunityCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCommunityCategories As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upUsers As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divUserError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUserError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUserError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAddNewUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewUser As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dropDialogUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogUsers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddUserCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddUserCommunity As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trUserCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUserCommunity As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dropDialogUserCommunities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDialogUserCommunities As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trUserAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUserAdmin As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''chkUserAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUserAdmin As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''trUserCommunitySubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUserCommunitySubmit As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''btnUserCommunitySubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUserCommunitySubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvUserCommunities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUserCommunities As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAB As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblABTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblABTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divABError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divABError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblABError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblABError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvAffectsBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAffectsBenefits As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upWWDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upWWDC As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divWWDCTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWWDCTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblWWDCTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWWDCTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divWWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWWDError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblWWDCError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWWDCError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvWWDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWWDC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMain As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkAddGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddGroup As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkAddCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkAddCommunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCommunity As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkAddCommunityCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCommunityCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkAddUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddUser As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblCustLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dropGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropGroups As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblCustLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustLabel1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dropCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropCategories As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvPriorities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPriorities As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
End Class
